### ISSUE TITLE
Make name optional or suggest a name automatically

### ISSUE THREAD

**Issue by joeriks** [leekelleher/umbraco-doc-type-grid-editor#14]
In many cases the user(editor) is not interested in making up a name for each item. (For example content with just an image and a rte).

I think it would be nice if it was possible to hide/disable the "name" property, or have it suggest a standard name (item1...).

**Comment by mattbrailsford** [comment]
The reason we have a name is for when previews aren't enabled, this way the editor can write a name that helps describe the piece of content. The problem with auto generating a name is that there is no easy way to count the existing number of items to be able to do "Item 1", "Item 2", etc, plus it kinda of defeats the purpose, ie, Item 1 isn't very descriptive.

Personally I don't see having to fill in a name being a big issue, but will be interesting to see what others think.

**Comment by leekelleher** [comment]
I did agree, but funny thing just happened (about 5 mins ago) ... I added a new DTGE, selected a DocType, entered the content, tried to save - it wouldn't close the panel.  I'd forgot to add a Name (yup, I was rushing).

I guess the question here is whether we enforce the Name field (and make it  more noticeable) - or - somehow automate the value for it?

I agree - default values like "Item 1" isn't great, (plus the grid-cells aren't incremental - so number suffixes don't make sense).

**Comment by mattbrailsford** [comment]
We could probably do similar to NC and use a label template, but I guess it depends if there is anything meaningful you can pull as a label (I think NC is more likely to have some kind of label for each item, where I don't see DTGE needing this).

Again, happy to hear suggestions on how we can do without it.

**Comment by leekelleher** [comment]
Maybe the default name could be the DocType alias?  (Only a thought :smile_cat:)

**Comment by mattbrailsford** [comment]
Could be, guess it's just what would you use if you use it twice?

**Comment by leekelleher** [comment]
AFAIK, we're nothing doing anything special with the names, right?

Multiple/duplicate classes aren't an issue, (since they aren't "real" nodes).  Unless I'm forgetting something?

**Comment by mattbrailsford** [comment]
No, we don't do anything with them, I just meant from the perspective of the grid preview when you don't have previews enabled. Could end up with a bunch of blocks the all say "MySpecialDocType", so no clue as to what the contents of the cells are.

**Comment by joeriks** [comment]
Yes, I like the label template in Archetype - until the content is not a simple text field. I don't think there's an easy way to, for example, display the name from a content/media picker (instead of the id).

The cshtml-preview, is in my opinion, one of the killer features of DTGE, and for all my current use cases it is probably what I will use. And otherwise I'd be very happy with a label template fallback (one could simple add a label property if needed, just for the backend use).

**Comment by leekelleher** [comment]
I agree, not ideal.  I'm meaning that we have a DocType alias as a fall-back, if the content-editor hasn't entered a Name.

**Comment by mattbrailsford** [comment]
As long as there is a means for people to change the label when previews aren't enabled I'm not really fussed so if we want to use a label template that falls back to the doc type alias, that sounds fine with me. I'll just require the dev using DTGE to setup a property to derive this from.

**Comment by Vrijdagonline** [comment]
Yesterday I did a demo for my content editors. Massive usage of the grid and much use of this cool DTGE package. Like Joerik is saying, I do too make a backend preview in the grid for every component. My content editors love every bit of it, but the only question I got was...
So if it is somehow possible to make the name optional, that would definitely be great.

**Comment by alanmac** [comment]
Hi folks, any more thoughts on bringing this into a release? From the comments above I think that an elegant solution is to remove the name field if previewing is enabled. It's not needed in that case if that's the way the developer intends it to be used. I feel it does disrupt the UX flow when this is a required field. 

Great package btw. Thanks.

**Comment by runegronkjaer** [comment]
I'm also running into this. Forgetting to write a name every single time and pushing save a few frustrating times. Finally realising I have to write a  name. :)
It should be optional to show that field or not. 

Otherwise it just works like a charm. Great work guys.

**Comment by mattbrailsford** [comment]
Fixed in commit 69797269181b5ad51a95f921d2da4cd336c2764b There is now no name field in the dialog, instead it will use the docTypeAlias be deafault, but you can override this be either a) having a property with the alias "name" on your doc type, or configuring a "nameTemplate" in the editor config file in a similar way to NC. So a config of:

    {
      "name": "Carousel",
      "alias": "carousel",
      "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
      "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
      "icon": "icon-pictures-alt-2",
      "config": {
        "allowedDocTypes": ["^Carousel$"],
        "nameTemplate": "{{title}}",
        "enablePreview": true,
        "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
        "previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
        "previewCssFilePath": "/css/fanoe.preview.css",
        "previewJsFilePath": ""
      }
    }

will result in the "title" field value being copied into the nodes Name field.

**Comment by alanmac** [comment]
thanks @mattbrailsford that's a great solution

**Comment by runegronkjaer** [comment]
Sounds great. That's perfekt

**Comment by SteveEdson** [comment]
Is this still supposed to be working (realise this is 3 years old now). The `nameTemplate` field doesn't seem to do anything, and the docs all seem out of date, they don't even mention the `previewCssFilePath` etc options.

Is it possible to change the name? I have an item of `Components`, and I select which component I want to use, however they all obviously just appear as "Components" when reordering.

Thanks.

**Comment by SteveEdson** [comment]
Is there any update on this? Still having issues where all of our components have the name of the DTGE group they are in, rather than the component doc type itself, making things very confusing. 

![image](https://user-images.githubusercontent.com/1201960/46345011-e9571000-c63a-11e8-9fd6-8f205ca208ff.png)

**Comment by leekelleher** [comment]
Hi @SteveEdson, can you open a new ticket for this one please? Could you add an example of your `nameTemplate` config too?  It's been a while since I've used that option myself, I'll see if it can refresh my memory of it. Thanks.
